[workspace]

members = [
	"kernel",
	"lib/rust/kernel",
	"lib/rust/pci",
	"lib/rust/virtio",
	"services/init/hello_world_virtio",
]

[profile.dev]
opt-level = 3
panic = "abort"
debug = true

[profile.release]
panic = "abort"
debug = true
lto = true
